version: "~> 1.0"

import:
  - source: netfoundry/ziti-ci:go-defaults.yml@build-info
  - source: netfoundry/ziti-ci:git-setup.yml@build-info
  - source: netfoundry/ziti-ci:versioning.yml@build-info
    if: type = pull_request

before_script:
  - ./tmp/ziti-ci generate-build-info ziti/sdkinfo/build_info.go sdkinfo
