version: "~> 1.0"

import:
  - source: netfoundry/ziti-ci:ziti-go-defaults.yml@v1
  - source: buildinfo.yml
    if: branch != update-dependency
  - source: trigger_downstreams.yml
    if: type != pull_request and branch != update-dependency
