apiVersion: apps/v1
kind: Deployment
metadata:
  name: reflect-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reflect-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: reflect-server
    spec:
      containers:
      - image: netfoundry/reflect-server:root
        name: reflect-server
        env:
        - name: IDENTITY_FILE # JSON file in same dir as this Compose file
          value: reflect-server.json
        - name: SERVICE_NAME  # Ziti service name to bind e.g. "ACME Reflect Server"
          value: "Ken Reflect Server"
        volumeMounts:
        - name: ziti-identity-json
          mountPath: "/identity"
          readOnly: true
#        securityContext:
#          runAsUser: 1000
#          runAsGroup: 1000
      restartPolicy: Always
      volumes:
      - name: ziti-identity-json
        secret:
          secretName: reflect-server.json
